name: "Download urls by regex and replace"
description: "Find images by url and download them in your build"
author: "Florian Schrag"
branding:
  icon: 'download'  
  color: 'purple'
inputs:
  include:
    description: "A glob of files to include in our find and replace"
    default: "**" # Include everything by default
    required: false
  exclude:
    description: "A glob of files to exclude in our find and replace"
    default: ".git/**" # Ignore the `.git` directory by default
    required: false
  find:
    description: "The regular expression (or fixed string) we want to fetch"
    required: true
  target:
    description: "The target file to fetch to it"
    required: true
  replace:
    description: "also replace with target url in file - default is true"
    required: false
  removeExif:
    description: "renove exif data - default is false"
    default: false
    required: false
outputs:
  modifiedFiles:
    description: "The number of files which a download has occured"
runs:
  using: "docker"
  image: "docker://ghcr.io/gitu/gha-download-images:v1.1.0"
